version: '3.8'

services:
  sso:
    depends_on: 
      ssodb:
        condition: service_healthy
        restart: true
    build:
      context: .
    image: sso
    container_name: sso
    networks:
      - ssonet
      - auth-network
    ports:
      - 44044:44044
    deploy:
      restart_policy:
        condition: on-failure
        
  ssodb:
    image: postgres:latest
    container_name: ssoDB
    env_file:
      - ./config.env
    networks:
      - ssonet
    volumes:
      - postgresql_ssodb:/var/lib/postgresql/ssodb
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}'"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 10s

volumes:
  postgresql_ssodb:

networks:
  ssonet:
    driver: bridge
  auth-network:
    driver: bridge
    external: true
  