# See: https://taskfile.dev/api/

version: "3"

tasks:
  generate:
    aliases:
      - migrations
    desc: "run migrations"
    cmds: 
      - go run ./cmd/migrate/ --storage-path=./storage/sso.db --migrations-path=./migrations
  generate_test:
    aliases:
      - migrations_test
    desc: "run test migrations"
    cmds: 
      - go run ./cmd/migrate/ --storage-path=./storage/sso.db --migrations-path=./tests/migrations --migrations-table=migrations_test